config/routes.rb
Rails.application.routes.draw do
  resources :medicines
  devise_for :users
  root 'medicines#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  validates :product, :strength, :dosage_form, :manufacturer, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  def show
    @medicine = Medicine.find(params[:id])
  end

  def index
    @medicines = Medicine.all
  end

  def new
    @medicine = Medicine.new
  end

  def create
    @medicine = Medicine.new(medicine_params)

    if @medicine.save
      redirect_to medicines_path
    else
      render :new
    end
  end

  def edit
    @medicine = Medicine.find(params[:id])
  end

  def update
    @medicine = Medicine.find(params[:id])
    if @medicine.update(medicine_params)
      redirect_to medicines_path
    else
      render :edit
    end
  end

  def destroy
    @medicine = Medicine.find(params[:id])

    @medicine.destroy

    redirect_to medicines_path
  end

  private

  def medicine_params
    params.require(:medicine).permit(:product, :strength, :dosage_form, :approval_number, :approval_date, :category, :manufacturer)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<!-- <footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2016 Rails101
        <br>Design by yourname

    </p>
</footer> -->

<footer>
<TABLE cellSpacing=0 cellPadding=0 width=1003 align=center border=0>
<TBODY>
<TR>
<TD height=90>
<TABLE  height=24 cellSpacing=0 cellPadding=0 align=center border=0>
<TBODY>
<TR>
<TD style="PADDING-LEFT: 20px" width="1024" align=middle bgColor=#003399>
  <FONT color=#ffffff>&copy; CFDA<BR>Constructed and Maintained by the Information Center of CFDA</FONT>
</TD>
</TR>
</TBODY>
</TABLE>
</TD>
</TR>
</TBODY>
</TABLE>
</footer>

app/views/common/_navbar.html.erb
<div class="navbar-wrap">
  <div class="navbar">
    <div class="fl">
      <a href="#">Welcome to Sourcing Pharma Website</a>
    </div>
    <ul class="fr">
      <% if !current_user %>
      <li class="fl">
        <%= link_to("Registration", new_user_registration_path) %>&nbsp
      </li>
      <li class="navbar-spacer fl"></li>
      <li class="fl pr10 pl10">
        &nbsp<%= link_to("Login", new_user_session_path) %>
      </li>
      <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
              <li> <%= link_to("Logout", destroy_user_session_path, method: :delete) %> </li>
          </ul>
        </li>
    <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>CFDA </title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <%= yield %>
        </div>

        <%= render "common/footer" %>

    </body>
</html>

app/views/medicines/edit.html.erb
<h1> Edit a medicine </h1>

<%= simple_form_for @medicine do |f| %>

<%= f.input :product %>
<%= f.input :strength %>
<%= f.input :dosage_form %>
<%= f.input :approval_number %>
<%= f.input :approval_date %>
<%= f.input :category %>
<%= f.input :manufacturer %>

  <%= f.submit "Submit" %>
<% end %>

app/views/medicines/index.html.erb
<table class="table table-boldered">
  <% @medicines.each do |medicine| %>
  <tr>
    <td>
      <%= link_to(medicine.product, medicine_path(medicine)) %>
    </td>
    <td>
      <%= medicine.strength %>
    </td>
    <td>
      <%= medicine.dosage_form %>
    </td>
    <td>
      <%= medicine.manufacturer %>
    </td>
  </tr>
  <% end %>
</table>

app/views/medicines/new.html.erb
<h1> Add a new medicine </h1>

<%= simple_form_for @medicine do |f| %>

<%= f.input :product %>
<%= f.input :strength %>
<%= f.input :dosage_form %>
<%= f.input :approval_number %>
<%= f.input :approval_date %>
<%= f.input :category %>
<%= f.input :manufacturer %>

  <%= f.submit "Submit" %>
<% end %>

app/views/medicines/show.html.erb
<table>
  <tr>
    <th>Product Name</th>
    <td><%= @medicine.product %></td>
  </tr>
  <tr>
    <th>Strength</th>
    <td><%= @medicine.strength %></td>
  </tr>
  <tr>
    <th>Dosage form</th>
    <td><%= @medicine.dosage_form %></td>
  </tr>
  <tr>
    <th>Approval number</th>
    <td><%= @medicine.approval_number %></td>
  </tr>
  <tr>
    <th>Approval date</th>
    <td><%= @medicine.approval_date %></td>
  </tr>
  <tr>
    <th>Category</th>
    <td><%= @medicine.category %></td>
  </tr>
  <tr>
    <th>Manufacture</th>
    <td><%= @medicine.manufacturer %></td>
  </tr>
</table>